### ISSUE TITLE
ssh key copied

### ISSUE THREAD

**Issue by AustinMCrane** [jcbwlkr/mydotfiles#2]
haha... so i used your dot files and it added your ssh key. Don't know if you planned on this to happen with yours. I didn't notice until i pushed some code to github and your sshkey was used.

**Comment by jcbwlkr** [comment]
I don't think my keys are in here (I was worried for a second lol) but I do have this https://github.com/jcbwlkr/mydotfiles/blob/master/home/.gitconfig

If you're using it directly then yeah it's going to put my name and email on your commits. But you shouldn't be able to do things like push to my repos. Can you confirm that's all it is?

**Comment by AustinMCrane** [comment]
That is probably it, I regenerated my key and it still shows you. Lol sorry for the scare dude. I wanted to make you aware!
